### PR TITLE
[FIX] use unique test fixtures

### LINKED ISSUE #36: Document usage of cli_test
If you have multiple tests with the same names in multiple cli tests, e.g.

cli_test1.cpp
```cpp
TEST_F(cli_test, some_test);
```

cli_test2.cpp
```cpp
TEST_F(cli_test, some_test);
```

the cli_test will construct test directories for each test. These directories will have the same name. It might happen that one test runs its `TearDown()` (deleting the directory) while the other test runs -> tests fail with cryptic errors.

One should create a new fixture for each cli_test:

cli_test.hpp
```cpp
struct cli_test1: public cli_test {};
struct cli_test2: public cli_test {};
```

cli_test1.cpp
```cpp
TEST_F(cli_test1, some_test);
```

cli_test2.cpp
```cpp
TEST_F(cli_test2, some_test);
```

### PR DESCRIPTION
**Pull request by eseiler**
Resolves #36

### CODE REVIEW

File: test/cli/cli_test.hpp [hunk 1]
```diff
@@ -93,3 +93,6 @@ struct cli_test : public ::testing::Test
         }
     }
 };
+
+// To prevent issues when running multiple CLI tests in parallel, give each CLI test unique names:
+struct fastq_to_fasta : cli_test {};
```
Comment (joergi-w) [inline test/cli/cli_test.hpp:98]: This is inheritance – isn't there an access specifier needed?
```suggestion
struct fastq_to_fasta : public cli_test {};
```

**Review by joergi-w — CHANGES_REQUESTED** [review]

File: test/cli/cli_test.hpp (hunk 1 above)
Comment (eseiler) [reply test/cli/cli_test.hpp]: `cli_test` is a struct, so the default visibility is `public`, but I agree that it is better to be verbose

**Review by joergi-w — APPROVED** [review]
Thanks :)
